//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPastelariaDoZe.WinFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoPastelariaDoZe.WinFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _null {
            get {
                object obj = ResourceManager.GetObject("null", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addNew {
            get {
                object obj = ResourceManager.GetObject("addNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apagar_solido_branco {
            get {
                object obj = ResourceManager.GetObject("apagar-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_solid_1_ {
            get {
                object obj = ResourceManager.GetObject("arrow-right-solid(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A aplicação conitnuará rodando em segundo plano.
        /// </summary>
        internal static string BalloonTipText_Text {
            get {
                return ResourceManager.GetString("BalloonTipText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastelaria do Zé.
        /// </summary>
        internal static string BalloonTipTitle_Text {
            get {
                return ResourceManager.GetString("BalloonTipTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barras_configuracoes_solido_branco {
            get {
                object obj = ResourceManager.GetObject("barras-configuracoes-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        internal static string buttonCadastrar_Text {
            get {
                return ResourceManager.GetString("buttonCadastrar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caixa.
        /// </summary>
        internal static string buttonCaixa_Text {
            get {
                return ResourceManager.GetString("buttonCaixa.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string buttonClientes_Text {
            get {
                return ResourceManager.GetString("buttonClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comandas.
        /// </summary>
        internal static string buttonComandas_Text {
            get {
                return ResourceManager.GetString("buttonComandas.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string buttonConfiguracoes_Text {
            get {
                return ResourceManager.GetString("buttonConfiguracoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string buttonEntrar_Text {
            get {
                return ResourceManager.GetString("buttonEntrar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string buttonFechar_Text {
            get {
                return ResourceManager.GetString("buttonFechar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        internal static string buttonFuncionarios_Text {
            get {
                return ResourceManager.GetString("buttonFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        internal static string buttonImportar_Text {
            get {
                return ResourceManager.GetString("buttonImportar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string buttonInicio_Text {
            get {
                return ResourceManager.GetString("buttonInicio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string buttonLogin_Text {
            get {
                return ResourceManager.GetString("buttonLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string buttonNao_Text {
            get {
                return ResourceManager.GetString("buttonNao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string buttonProdutos_Text {
            get {
                return ResourceManager.GetString("buttonProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string ButtonSalvar_Text {
            get {
                return ResourceManager.GetString("ButtonSalvar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string buttonSalvarIdioma_Text {
            get {
                return ResourceManager.GetString("buttonSalvarIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string buttonSim_Text {
            get {
                return ResourceManager.GetString("buttonSim.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string buttonSobre_Text {
            get {
                return ResourceManager.GetString("buttonSobre.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caixa_solido_branco {
            get {
                object obj = ResourceManager.GetObject("caixa-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar para aplicar o novo idioma imediatamente.
        /// </summary>
        internal static string checkBoxReiniciar_Text {
            get {
                return ResourceManager.GetString("checkBoxReiniciar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clientes_solido_branco {
            get {
                object obj = ResourceManager.GetObject("clientes-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comanda_solido_branco {
            get {
                object obj = ResourceManager.GetObject("comanda-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editar_solido_branco {
            get {
                object obj = ResourceManager.GetObject("editar-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fechar_solido_branco {
            get {
                object obj = ResourceManager.GetObject("fechar-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string formClientes_Text {
            get {
                return ResourceManager.GetString("formClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comandas.
        /// </summary>
        internal static string formComandas_Text {
            get {
                return ResourceManager.GetString("formComandas.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string formConfiguracoes_Text {
            get {
                return ResourceManager.GetString("formConfiguracoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        internal static string formFuncionarios_Text {
            get {
                return ResourceManager.GetString("formFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiados do Zé.
        /// </summary>
        internal static string formInicio_Text {
            get {
                return ResourceManager.GetString("formInicio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string formLogin_Text {
            get {
                return ResourceManager.GetString("formLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string formProdutos_Text {
            get {
                return ResourceManager.GetString("formProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string formSobre_Text {
            get {
                return ResourceManager.GetString("formSobre.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap funcionarios_solido_branco {
            get {
                object obj = ResourceManager.GetObject("funcionarios-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inicio_solido_branco {
            get {
                object obj = ResourceManager.GetObject("inicio-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string labelCPF_Text {
            get {
                return ResourceManager.GetString("labelCPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string labelDescricao_Text {
            get {
                return ResourceManager.GetString("labelDescricao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja sair?.
        /// </summary>
        internal static string labelDesejaSair_Text {
            get {
                return ResourceManager.GetString("labelDesejaSair.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia do fiado (0 - dias corridos).
        /// </summary>
        internal static string labelDiaDoFiado_Text {
            get {
                return ResourceManager.GetString("labelDiaDoFiado.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string labelFoto_Text {
            get {
                return ResourceManager.GetString("labelFoto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string labelGrupo_Text {
            get {
                return ResourceManager.GetString("labelGrupo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string labelLogin_Text {
            get {
                return ResourceManager.GetString("labelLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca fiado?.
        /// </summary>
        internal static string labelMarcaFiado_Text {
            get {
                return ResourceManager.GetString("labelMarcaFiado.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        internal static string labelMatricula_Text {
            get {
                return ResourceManager.GetString("labelMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multa por atraso (R$).
        /// </summary>
        internal static string labelMultaPorAtraso_Text {
            get {
                return ResourceManager.GetString("labelMultaPorAtraso.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo usuário?.
        /// </summary>
        internal static string labelNovoUsuario_Text {
            get {
                return ResourceManager.GetString("labelNovoUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa de juros diária (%).
        /// </summary>
        internal static string labelTaxaJurosDiaria_Text {
            get {
                return ResourceManager.GetString("labelTaxaJurosDiaria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string labelTelefone_Text {
            get {
                return ResourceManager.GetString("labelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em desenvolvimento....
        /// </summary>
        internal static string labelTextoTemporario_Text {
            get {
                return ResourceManager.GetString("labelTextoTemporario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor unitário (R$).
        /// </summary>
        internal static string labelValorUnitario_Text {
            get {
                return ResourceManager.GetString("labelValorUnitario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicando aplicação para alterar idioma.
        /// </summary>
        internal static string MessageBox_Text {
            get {
                return ResourceManager.GetString("MessageBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap null1 {
            get {
                object obj = ResourceManager.GetObject("null1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap produtos_solido_branco {
            get {
                object obj = ResourceManager.GetObject("produtos-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string radioButtonAdmin_Text {
            get {
                return ResourceManager.GetString("radioButtonAdmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balcão.
        /// </summary>
        internal static string radioButtonBalcao_Text {
            get {
                return ResourceManager.GetString("radioButtonBalcao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string radioButtonFiadoNao_Text {
            get {
                return ResourceManager.GetString("radioButtonFiadoNao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string radioButtonFiadoSim_Text {
            get {
                return ResourceManager.GetString("radioButtonFiadoSim.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap salvar_solido_branco {
            get {
                object obj = ResourceManager.GetObject("salvar-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seta_direita_branca {
            get {
                object obj = ResourceManager.GetObject("seta-direita-branca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sobre_solido_branco {
            get {
                object obj = ResourceManager.GetObject("sobre-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma/Região.
        /// </summary>
        internal static string tabPageIdiomaRegiao_Text {
            get {
                return ResourceManager.GetString("tabPageIdiomaRegiao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros para cobrança.
        /// </summary>
        internal static string tabPageParametros_Text {
            get {
                return ResourceManager.GetString("tabPageParametros.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.000.000-00.
        /// </summary>
        internal static string textBoxCPF_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxCPF.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do produto.
        /// </summary>
        internal static string textBoxDescricaoProduto_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxDescricaoProduto.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000.
        /// </summary>
        internal static string textBoxMatricula_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxMatricula.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R$.
        /// </summary>
        internal static string textBoxMultaPorAtraso_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxMultaPorAtraso.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string textBoxNome_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxNome.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do funcionário.
        /// </summary>
        internal static string textBoxNomeFuncionario_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxNomeFuncionario.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do produto.
        /// </summary>
        internal static string textBoxNomeProduto_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxNomeProduto.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ******.
        /// </summary>
        internal static string textBoxSenha_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxSenha.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string textBoxTaxaJurosDiaria_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxTaxaJurosDiaria.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (00) 0 0000 0000.
        /// </summary>
        internal static string textBoxTelefone_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxTelefone.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R$.
        /// </summary>
        internal static string textBoxValorUnitario_PlaceholderText {
            get {
                return ResourceManager.GetString("textBoxValorUnitario.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string toolStripMenuItemClientes_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string toolStripMenuItemConfiguracoes_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemConfiguracoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        internal static string toolStripMenuItemFuncionarios_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string toolStripMenuItemInicio_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemInicio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string toolStripMenuItemLogin_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string toolStripMenuItemProdutos_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string toolStripMenuItemSair_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemSair.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string toolStripMenuItemSobre_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemSobre.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string toolStripMenuItemSystemTrayAbrir_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemSystemTrayAbrir.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string toolStripMenuItemSystemTraySair_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemSystemTraySair.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string toolStripMenuItemSystemTraySobre_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemSystemTraySobre.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_friends_solid {
            get {
                object obj = ResourceManager.GetObject("user-friends-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
