//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPastelariaDoZe.WinFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoPastelariaDoZe.WinFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apagar_solido_branco {
            get {
                object obj = ResourceManager.GetObject("apagar-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_solid_1_ {
            get {
                object obj = ResourceManager.GetObject("arrow-right-solid(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barras_configuracoes_solido_branco {
            get {
                object obj = ResourceManager.GetObject("barras-configuracoes-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string button {
            get {
                return ResourceManager.GetString("button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        internal static string buttonCadastrar_Text {
            get {
                return ResourceManager.GetString("buttonCadastrar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caixa.
        /// </summary>
        internal static string buttonCaixa_Text {
            get {
                return ResourceManager.GetString("buttonCaixa.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string buttonCliente_Text {
            get {
                return ResourceManager.GetString("buttonCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comanda.
        /// </summary>
        internal static string buttonComanda_Text {
            get {
                return ResourceManager.GetString("buttonComanda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string buttonConfiguracoes_Text {
            get {
                return ResourceManager.GetString("buttonConfiguracoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string buttonEntrar_Text {
            get {
                return ResourceManager.GetString("buttonEntrar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string buttonFechar_Text {
            get {
                return ResourceManager.GetString("buttonFechar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        internal static string buttonFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        internal static string buttonImportar {
            get {
                return ResourceManager.GetString("buttonImportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string buttonInicio_Text {
            get {
                return ResourceManager.GetString("buttonInicio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string buttonLogin_Text {
            get {
                return ResourceManager.GetString("buttonLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        internal static string buttonProduto_Text {
            get {
                return ResourceManager.GetString("buttonProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string buttonSobre_Text {
            get {
                return ResourceManager.GetString("buttonSobre.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caixa_solido_branco {
            get {
                object obj = ResourceManager.GetObject("caixa-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clientes_solido_branco {
            get {
                object obj = ResourceManager.GetObject("clientes-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comanda_solido_branco {
            get {
                object obj = ResourceManager.GetObject("comanda-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editar_solido_branco {
            get {
                object obj = ResourceManager.GetObject("editar-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fechar_solido_branco {
            get {
                object obj = ResourceManager.GetObject("fechar-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiados do Zé.
        /// </summary>
        internal static string form_Text {
            get {
                return ResourceManager.GetString("form.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap funcionarios_solido_branco {
            get {
                object obj = ResourceManager.GetObject("funcionarios-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inicio_solido_branco {
            get {
                object obj = ResourceManager.GetObject("inicio-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string labelDescricao_Text {
            get {
                return ResourceManager.GetString("labelDescricao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string labelFoto {
            get {
                return ResourceManager.GetString("labelFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo usuário?.
        /// </summary>
        internal static string labelNovoUsuario_Text {
            get {
                return ResourceManager.GetString("labelNovoUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar-se.
        /// </summary>
        internal static string labelTituloCadastro_Text {
            get {
                return ResourceManager.GetString("labelTituloCadastro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor unitário (R$).
        /// </summary>
        internal static string labelValorUnitario_Text {
            get {
                return ResourceManager.GetString("labelValorUnitario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap produtos_solido_branco {
            get {
                object obj = ResourceManager.GetObject("produtos-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap salvar_solido_branco {
            get {
                object obj = ResourceManager.GetObject("salvar-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seta_direita_branca {
            get {
                object obj = ResourceManager.GetObject("seta-direita-branca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sobre_solido_branco {
            get {
                object obj = ResourceManager.GetObject("sobre-solido-branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string textBoxSeuNome_Placeholder {
            get {
                return ResourceManager.GetString("textBoxSeuNome.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R$.
        /// </summary>
        internal static string textBoxValorUnitario_Placeholder {
            get {
                return ResourceManager.GetString("textBoxValorUnitario.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectar-se.
        /// </summary>
        internal static string txtJanelaLogin {
            get {
                return ResourceManager.GetString("txtJanelaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_friends_solid {
            get {
                object obj = ResourceManager.GetObject("user-friends-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
